### ISSUE TITLE
Возможно в части оповещений отказаться от broadcast

### ISSUE THREAD

**Issue by nkiryanov** [fandsdev/websockets-notifications-py#17]
Отсюад #14

> 3. Предлагаю убрать [broadcast](https://github.com/fandsdev/websockets-notifications-py/blob/main/src/consumer/consumer.py#L71), [тут](https://github.com/fandsdev/websockets-notifications-py/blob/main/src/handlers/websockets_access_guardian.py#L42) и может быть где-то еще, чтобы заменить на цикл с await connection.send(data), тк. синхронный broadcast может вести к [переполнению](https://websockets.readthedocs.io/en/stable/intro/tutorial2.html#broadcast) буфера. Бродкаст лучше имплементировать, если понятны риски.

**Comment by nkiryanov** [comment]
> тк. синхронный broadcast может вести к [переполнению](https://websockets.readthedocs.io/en/stable/intro/tutorial2.html#broadcast) буфера. Бродкаст лучше имплементировать, если понятны риски.

@kazqvaizer вообще думал об этом и я бы оставил синхронный broadcast — с учётом что отправляем сообщения не часто (например раз в 60 секунд) то вряд ли будем переполнять буфер — keepalive по дефолту для вебсокетов в библиотеке 30 сек и мертвые клиенты будут отваливаться.
А вот наивная реализация будет приводить к тому, что один мертвый клиент будет останавливать оповещения остальных клиентов.

Вот [тут](https://websockets.readthedocs.io/en/stable/topics/broadcast.html) ментейнер описывает подходы. Все это прочитал и по этой логике кажись можем на backpressure тут забить.

Или я что-то не учёл?

**Comment by kazqvaizer** [comment]
> Или я что-то не учёл?

Не, кажется что все учел. Сейчас вообще тут задача кажется уже зависимой от бизнес задачи и на темплейт для вебсокетов не влияет. Закрою
